# Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [8]:
def myFunction(n):
    try:
        return print(n/0)
    except Exception as e :
        print("The exception is",e)
myFunction(5)

The exception is division by zero


# Task 2
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket

In [10]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
      for v in verbs:
        for o in objects:
          print(s+" "+v+" "+o+".")


Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 3
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [21]:
import numpy as np
x = np.array([1, 2, 3, 5])
print("----------------------------------------------------------------")
print("                          True")
print("----------------------------------------------------------------")
print(np.vander(x, increasing=True))
print("----------------------------------------------------------------")
print("                           False")
print("----------------------------------------------------------------")

print(np.vander(x, increasing=False))

----------------------------------------------------------------
                          True
----------------------------------------------------------------
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
----------------------------------------------------------------
                           False
----------------------------------------------------------------
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
