# 1
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [1]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [2]:
x = np.array([1, 2, 3, 5])
np.vander(x)
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [3]:
x = np.array([1, 2, 3, 5])
np.vander(x)
np.vander(x, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

# 2
Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
n= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
li=[]
k=3
for count in range(len(n)-1):
    li.append(n[count:count+k])
    
y=[]
for count_i in range(len(li)-1):
#     print(np.cumsum(li[count_i])[2]/3)
    y.append(np.cumsum(li[count_i])[2]/3)
print(y)
print("\nThe moving average sequence has " + str(len(y))+" values")



[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]

The moving average sequence has 11 values
